### ISSUE TITLE
Cannot use sturgeon-connect

### ISSUE THREAD

**Issue by copy** [jhjourdan/statmemprof-emacs#2]
I'm on a  4.05.0+statistical-memprof switch. After adding `Statmemprof_emacs.start 1E-4 30 5` to my program it creates a socket in `/tmp/sturgeon.1000/main.exememprof.19455.sturgeon`, so that part seems to work fine.

However in emacs, when using `M-x sturgeon-connect` and selecting the socket file, it prints `/tmp/sturgeon.1000/main.exememprof.19455.sturgeon exited with status 126`.

**Comment by copy** [comment]
Apparently an ``eval `opam config env``` or emacs restart was necessary. Apologies for the noise.

**Comment by jhjourdan** [comment]
Happy to see that the issue is solved :)

The issue seems to be related to sturgeon, so posting an issue [there](https://github.com/let-def/sturgeon/issues) would probably be a etter idea.
