### ISSUE TITLE
Instructions for sturgeon-connect incomplete

### ISSUE THREAD

**Issue by psteckler** [jhjourdan/statmemprof-emacs#5]
The `README` says only: "type M-x sturgeon-connect"

When you do that, you're prompted for a socket, and the instructions here don't tell you how to find that.

For me, I found the socket in `/tmp/sturgeon.1000/`, apparently created by the executable I'd run with the call to `Statmemprof_emacs.start`. I entered that filename, not including the path; that worked.

**Comment by let-def** [comment]
Completion should work in this field. Can you confirm that `[tab]` give the possible names for the socket? (Provided you started the application before doing M-X sturgeon-connect)

**Comment by psteckler** [comment]
Yes, tabbing does the autocomplete, once the socket is created.

You might mention this in the instructions.
